### ISSUE TITLE
Fix notebook working directory path

### ISSUE THREAD

**Issue by Emre-Yorat89** [pypsa-meets-earth/documentation#36]
Hello,

I have experienced ModuleNotFoundError: No module named '_helpers' error because of directory path in 0build_shapes notebook. It is indicated in notebooks part https://pypsa-earth.readthedocs.io/en/latest/notebooks.html that you have to make a folder named "pypsa-earth-project" and clone the project in that folder. However it is not pointed out in https://github.com/pypsa-meets-earth/pypsa-earth and https://pypsa-earth.readthedocs.io/en/latest/installation.html. This may be specified in these links.
In other notebooks such as 0shape_comparison it is clearly understood where to insert your directory path for example the code block os.chdir(r"C:\Users\User\Documents\pypsa\pypsa-earth"). 

Have a great day.

**Comment by pz-max** [comment]
Across all jupyter notebooks we should adjust the path setting to be easier & more resistant:
Example described and discussed here: https://github.com/pypsa-meets-earth/documentation/pull/39#issuecomment-1331165963
Snippet:
```python
import os
import sys

if not os.path.isdir("./pypsa-earth"):
    os.chdir("../../..")  # this moves the current directory to the parent of documentation folder, where pypsa-earth folder shall be located as well
    sys.path.append("pypsa-earth/scripts")  # this adds the pypsa-earth/scripts folder into the path
```
