### ISSUE TITLE
Update installations instructions in the hackathon materials

### ISSUE THREAD

**Issue by ekatef** [pypsa-meets-earth/documentation#5]
The installation procedure was being tested extensively throughout last months. The elaborated practical recommendations should be introduced into the installation notebook https://github.com/pypsa-meets-earth/documentation/blob/main/hackathon/2_installation_pypsaafrica.ipynb

**Comment by ekatef** [comment]
@pz-max, probably this one may be helpful as well to provide installation instructions

**Comment by pz-max** [comment]
yeah probably just a bit too long. We could link from the readthedocs to this installation instructions (and the software hints) in case they have problems
