### ISSUE TITLE
Include a section on hydro in the build_renewable_profile notebook

### ISSUE THREAD

**Issue by asolavi** [pypsa-meets-earth/documentation#54]
Create a section on hydro in the [build_renewable_profile.ipynb notebook](https://github.com/pypsa-meets-earth/documentation/blob/main/notebooks/build_renewable_profiles.ipynb), detailing the process made to create the hydro time series. Currently, built_renewable_profile.ipynb focuses on wind and solar.

Hydro modelling is done in three steps:

1. Preparation of hydro-potential data with atlite: ERA5 reanalysis dataset is used, runoff is being integrated across hydrobasins assuming some flow speed and put into cutout. This is done [here](https://github.com/PyPSA/atlite/blob/cc4ce153ad5885df164ac0706efc847090b22e15/atlite/hydro.py#L83-L106). More details in the methodology used by atlite can be found [here](https://atlite.readthedocs.io/en/latest/ref_api.html#atlite.Cutout.hydro).

2. The output of the time series obtained in step 1 (cutout hydro potential) is normalized in pypsa-earth using the normalization procedure described [here](https://github.com/pypsa-meets-earth/pypsa-earth/blob/186d2d23f6fad955e8a2f253e08c8b129af0e423/scripts/build_renewable_profiles.py#L315C61-L315C61). This is done to match country statistics. The result is stored in `resources/renewable_profiles/profile_hydro.nc`.

3. Attach_hydro in add_electricity, as described [here](https://github.com/pypsa-meets-earth/pypsa-earth/blob/186d2d23f6fad955e8a2f253e08c8b129af0e423/scripts/add_electricity.py#L443). Specifies how the different hydro types (runoff river (`ror`), hydro dams (`hydro`), and pumped storage (`PHS`) are added to the network in `add_electricity`.

**Comment by AnasAbuzayed** [comment]
can be helpful: 
https://pypsa-eur.readthedocs.io/en/latest/preparation.html#module-build_hydro_profile
